server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: localhost

spring:
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    name: service-registry
