server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/order/**
    config:
      enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://${service_registry:localhost}:8761/eureka/






#
#server:
#  port: 8080
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 60000
#  instance:
#    hostname: localhost
#  service-url:
#    defaultZone: http://${service_registry:localhost}:8761/eureka/
#
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id : product-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#        - id: order-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#      enable-cors: true
