
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${db_url:localhost}:3306/vibze
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: product-service



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: localhost
    prefer-ip-address: true
  service-url:
    defaultZone: http://${service_registry:localhost}:8761/eureka/
